create table if not exists sensor
(
    from_value  integer
        constraint sensor_from_value_check
            check (from_value >= 0),
    to_value    integer
        constraint sensor_to_value_check
            check (to_value >= 0),
    id          bigint generated by default as identity
        primary key,
    model       varchar(15)  not null,
    name        varchar(30)  not null,
    location    varchar(40),
    description varchar(200),
    type        varchar(255) not null
        constraint sensor_type_check
            check ((type)::text = ANY
        ((ARRAY ['PRESSURE'::character varying, 'VOLTAGE'::character varying, 'TEMPERATURE'::character varying, 'HUMIDITY'::character varying])::text[])),
    unit        varchar(255)
        constraint sensor_unit_check
            check ((unit)::text = ANY
                   ((ARRAY ['BAR'::character varying, 'VOLTAGE'::character varying, 'CELSIUM'::character varying, 'PERCENT'::character varying])::text[]))
);

alter table sensor
    owner to "user";


create table if not exists users
(
    id       bigint       not null
        primary key,
    email    varchar(255) not null
        unique,
    password varchar(255) not null,
    role     varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
    username varchar(255) not null
        unique
);

alter table users
    owner to "user";



